### ISSUE TITLE
Update 13 for Raft

### ISSUE THREAD

**Issue by Aidanamite** [burnedram/raftmod-autorecipe#2]
The recent game update has broken the mod ability to load. If you aren't planning to update the mod yourself would you be okay with me updating it so that it remains functional?

**Comment by spannerman79** [comment]
This has issue with the Electric Cookingpot from your mod https://www.raftmodding.com/mods/electricity-mod @Aidanamite  at this current time.

Versions 1.0.7 (@Aidanamite mod) and Version 1.1.2 for auto recipe redux

**Comment by Aidanamite** [comment]
2 things:
1. this isn't the place for that report as this github repo isn't connected to either mod
2. the mod incompatibility is probably caused by auto recipe redux not the electricity mod

**Comment by spannerman79** [comment]
>this isn't the place for that report as this github repo isn't connected to either mod

I suggest that you look at the actual link provided, I'll even highlight it https://www.raftmodding.com/mods/auto-recipe-redux#:~:text=source%20code%20repository%20

The source/git provided in fact points to **this** repo.

**Comment by Aidanamite** [comment]
ah, based on the owner of the repo and repo name I assumed this was still the old mod but it looks like the repo has been updated to be the redux version.

Still, I think adding to this report is not the place to bring up the issue. Either create a new issue report here for the issue in question or post it in the [mods-incompatibilities](https://discord.com/channels/1029828896935383093/1062193293150126301) channel on the raft modding discord.

Make sure to include all details in the report to. just saying it's incompatible isn't helpful, describe what is or is not happening and include error screenshots/logs if applicable
